name: 'local-cache-restore'
description: "Restore files from a local cache on the runner's file system"
inputs:
  key:
    description: 'An explicit key for versioning the cache'
    required: false
  path:
    description: 'The file(s) or folder(s) to restore from cache. Can be a single path or multiline paths.'
    required: true
  restore-keys:
    description: 'An ordered list of keys to use for restoring the cache if no cache hit occurred for key'
    required: false
  strategy:
    description: 'Caching mechanism to be used'
    required: false
    default: 'move'
  fail-on-cache-miss:
    description: 'Fail the workflow if the cache cannot be found'
    required: false
    default: 'false'
outputs:
  cache-hit:
    description: 'A boolean value to indicate if cache was found and restored (true if at least one path was cached)'
  restored-key:
    description: 'The key that was used to restore the cache (can be primary key or one of the restore-keys)'
runs:
  using: 'node16'
  main: '../dist/main.js'