name: 'local-cache-save'
description: "Save files to a local cache on the runner's file system"
inputs:
  key:
    description: 'An explicit key for versioning the cache'
    required: false
  path:
    description: 'The file(s) or folder(s) to be cached. Can be a single path or multiline paths.'
    required: true
  strategy:
    description: 'Caching mechanism to be used'
    required: false
    default: 'copy'
  save-always:
    description: 'For documentation only - This parameter is not used in the save action as it runs explicitly'
    required: false
    default: 'false'
runs:
  using: 'node16'
  main: '../dist/post.js'